/**
 * Extracts only the icons this site uses out of @iconify-json/lucide
 * and writes them to lib/icons.generated.ts.
 *
 * Why: @iconify-json/lucide ships one 582 kB icons.json with no per-icon
 * entry point, so importing it directly bundles every Lucide icon. There
 * is nothing for a bundler to tree-shake. This script is the tree shake.
 *
 *   bun run icons
 */
import { writeFileSync } from "node:fs";
import set from "@iconify-json/lucide/icons.json" with { type: "json" };

const NAMES = [
  "arrow-down",
  "arrow-left",
  "arrow-up-right",
  "check",
  "file-text",
  "git-branch",
  "hash",
  "mail",
  "menu",
  "monitor",
  "moon",
  "plus",
  "search",
  "sun",
  "x",
] as const;

type IconBody = { body: string; width?: number; height?: number };

const icons: Record<string, IconBody> = {};
const missing: string[] = [];

for (const name of NAMES) {
  const direct = (set.icons as Record<string, IconBody>)[name];
  if (direct) {
    icons[name] = direct;
    continue;
  }

  // one level of alias indirection is all Iconify sets use
  const alias = (set.aliases as Record<string, { parent: string }> | undefined)?.[
    name
  ];
  const parent = alias && (set.icons as Record<string, IconBody>)[alias.parent];
  if (parent) {
    icons[name] = parent;
    continue;
  }

  missing.push(name);
}

if (missing.length) {
  throw new Error(`Not in @iconify-json/lucide: ${missing.join(", ")}`);
}

const out = `// Generated by scripts/generate-icons.ts — do not edit.
// Run \`bun run icons\` after changing the NAMES list in that script.
import type { IconifyJSON } from "@iconify/types";

export type IconName = ${NAMES.map((n) => `"${n}"`).join(" | ")};

export const lucideSubset: IconifyJSON = ${JSON.stringify(
  { prefix: "lucide", width: set.width, height: set.height, icons },
  null,
  2,
)};
`;

writeFileSync("lib/icons.generated.ts", out);
console.log(
  `wrote lib/icons.generated.ts — ${NAMES.length} icons, ${(out.length / 1024).toFixed(1)} kB`,
);
